# GitHub Action Metadata file for defining the action
name: 'Run .NET Framework SDK Program'
description: 'Executes program operation within a Microsoft Windows Docker container. Supports projects using .NET Framework 4.8, 4.7.2, 4.7.1, 4.7, 4.6.2, 3.5, 3.0, and 2.5'
author: 'ZombieMaker'
inputs:
  dotnet-framework-version:
    description: '.NET Framework version'
    required: true
    default: '4.8'
  command:
    description: 'Single or multiple command and parameters (one per line)'
    required: true
    default: ''
  working-directory:
    description: 'Directory where .NET solution or project files are located'
    required: true
    default: '${{ github.workspace }}'
runs:
  using: "composite"
  steps:
    # - name: Check GitHub Action Runner host for Docker
    #   run: |
    #     docker ps; `
    #     docker version
    #   shell: pwsh
    
    - name: Check Action Runner current working directory
      run: write-host "Current working directory is $(pwd)"
      shell: pwsh
    
    - name: Display command string
      run: |
        $commandString = @'
        ${{ inputs.command }}
        '@; `
        write-host "******* COMMAND STRING *******"; `
        write-host "$commandString"; `
        write-host "*******************************"; `
      shell: pwsh
    
    # Handling command strings that have either double or single quotes
    # TIP: Do not use PowerShell comments in this action definition for action parameters.  
    # The GitHub Action Runner will simply expand all ${{ inputs.VARIABLE }} even in commented run lines
    - name: Execute command using task container
      run: |
        # Use here-string to encapsulate any single or double quoting
        $inputHereString = @'
        ${{ inputs.command }}
        '@; `
        Import-Module ${{ github.action_path }}\scripts\gha-pshell-module.psm1; `
        Invoke-ContainerizedDotnetSdkCommand -DotnetFrameworkVersion ${{ inputs.dotnet-framework-version }} -ContainerHostWorkingDirectory "${{ inputs.working-directory }}" -GitHubActionPath "${{ github.action_path }}" -CommandString $inputHereString -IsHereString -Debug;
      shell: pwsh